// <auto-generated />
using System;
using GIS.API.Abstractions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GIS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119164920_update_pk")]
    partial class update_pk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GIS.API.Models.Ca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("GioBD")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKT")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MaCa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaCa")
                        .IsUnique();

                    b.ToTable("Ca", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 400, DateTimeKind.Local).AddTicks(8860),
                            CreatedBy = "system",
                            GioBD = new TimeSpan(0, 8, 0, 0, 0),
                            GioKT = new TimeSpan(0, 12, 59, 59, 0),
                            IsActive = true,
                            MaCa = "CA01",
                            TenCa = "Ca làm việc 01"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 400, DateTimeKind.Local).AddTicks(8900),
                            CreatedBy = "system",
                            GioBD = new TimeSpan(0, 13, 0, 0, 0),
                            GioKT = new TimeSpan(0, 18, 0, 0, 0),
                            IsActive = true,
                            MaCa = "CA02",
                            TenCa = "Ca làm việc 02"
                        });
                });

            modelBuilder.Entity("GIS.API.Models.ChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiaDiemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Gio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("TheId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiaDiemId");

                    b.HasIndex("TheId", "DiaDiemId");

                    b.ToTable("ChamCong", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(3880),
                            CreatedBy = "system",
                            DiaDiemId = 1,
                            Gio = new DateTime(2025, 12, 30, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            TheId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(3890),
                            CreatedBy = "system",
                            DiaDiemId = 1,
                            Gio = new DateTime(2025, 12, 30, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            TheId = 2
                        });
                });

            modelBuilder.Entity("GIS.API.Models.Diem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MaDiaDiem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("X")
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal>("Y")
                        .HasColumnType("decimal(18,10)");

                    b.HasKey("Id");

                    b.HasIndex("MaDiaDiem")
                        .IsUnique();

                    b.ToTable("Diem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8410),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "CNC_P1",
                            TenDiaDiem = "Điểm CNC 1",
                            X = 106.79275610764999m,
                            Y = 10.857783206346067m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8420),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "CNC_P2",
                            TenDiaDiem = "Điểm CNC 2",
                            X = 106.79328139312916m,
                            Y = 10.856927577461303m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8420),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "CNC_P3",
                            TenDiaDiem = "Điểm CNC 3",
                            X = 106.79344256846417m,
                            Y = 10.857020044112776m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8420),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "CNC_P4",
                            TenDiaDiem = "Điểm CNC 4",
                            X = 106.79346171800893m,
                            Y = 10.856999670107276m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8420),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "CNC_P5",
                            TenDiaDiem = "Điểm CNC 5",
                            X = 106.79366597981964m,
                            Y = 10.857121914119407m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8420),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "CNC_P6",
                            TenDiaDiem = "Điểm CNC 6",
                            X = 106.79365002186567m,
                            Y = 10.857145422577535m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8420),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "CNC_P7",
                            TenDiaDiem = "Điểm CNC 7",
                            X = 106.79365321345647m,
                            Y = 10.857150124268943m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8430),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "CNC_P8",
                            TenDiaDiem = "Điểm CNC 8",
                            X = 106.79368193777358m,
                            Y = 10.857170498264162m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8430),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "CNC_P9",
                            TenDiaDiem = "Điểm CNC 9",
                            X = 106.79318245380306m,
                            Y = 10.858034040945556m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8430),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "HC_P1",
                            TenDiaDiem = "HC 1",
                            X = 106.79199457149355m,
                            Y = 10.858451185832704m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8430),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "HC_P2",
                            TenDiaDiem = "HC 2",
                            X = 106.79217819040733m,
                            Y = 10.858141616895171m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8430),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "HC_P3",
                            TenDiaDiem = "HC 3",
                            X = 106.79225469828806m,
                            Y = 10.85818970529487m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8430),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "HC_P4",
                            TenDiaDiem = "HC 4",
                            X = 106.7923618093211m,
                            Y = 10.85802440138849m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8430),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "HC_P5",
                            TenDiaDiem = "HC 5",
                            X = 106.79275046935523m,
                            Y = 10.858261837879885m
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8440),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "HC_P6",
                            TenDiaDiem = "HC 6",
                            X = 106.79247504098457m,
                            Y = 10.858715671661097m
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8440),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "IT_P1",
                            TenDiaDiem = "IT 1",
                            X = 106.79249646319826m,
                            Y = 10.858724688215423m
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8440),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "IT_P2",
                            TenDiaDiem = "IT 2",
                            X = 106.79271680589477m,
                            Y = 10.85834899805968m
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8440),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "IT_P3",
                            TenDiaDiem = "IT 3",
                            X = 106.7927718915689m,
                            Y = 10.85838205881235m
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8440),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "IT_P4",
                            TenDiaDiem = "IT 4",
                            X = 106.79278413282982m,
                            Y = 10.858364025674982m
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8440),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "IT_P5",
                            TenDiaDiem = "IT 5",
                            X = 106.79276271062322m,
                            Y = 10.85834899805968m
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8440),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "IT_P6",
                            TenDiaDiem = "IT 6",
                            X = 106.7928116756669m,
                            Y = 10.858279871019555m
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8450),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "IT_P7",
                            TenDiaDiem = "IT 7",
                            X = 106.79291266606945m,
                            Y = 10.85834899805968m
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8450),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "IT_P8",
                            TenDiaDiem = "IT 8",
                            X = 106.79286676134103m,
                            Y = 10.858436158217911m
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8450),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "IT_P9",
                            TenDiaDiem = "IT 9",
                            X = 106.7929585707979m,
                            Y = 10.858487252091944m
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8450),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "IT_P10",
                            TenDiaDiem = "IT 10",
                            X = 106.79272904715569m,
                            Y = 10.858871958627553m
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8450),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "TD_P1",
                            TenDiaDiem = "TD 1",
                            X = 106.79171302248945m,
                            Y = 10.859181526817972m
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8450),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "TD_P2",
                            TenDiaDiem = "TD 2",
                            X = 106.79198845086007m,
                            Y = 10.85871867718647m
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8460),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "TD_P3",
                            TenDiaDiem = "TD 3",
                            X = 106.79223327607843m,
                            Y = 10.85886294208362m
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8460),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "TD_P4",
                            TenDiaDiem = "TD 4",
                            X = 106.7922791808069m,
                            Y = 10.858745726859997m
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8460),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "TD_P5",
                            TenDiaDiem = "TD 5",
                            X = 106.79250258381865m,
                            Y = 10.858868953119481m
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8460),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "TD_P6",
                            TenDiaDiem = "TD 6",
                            X = 106.79242913625313m,
                            Y = 10.858971140710741m
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8460),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "TD_P7",
                            TenDiaDiem = "TD 7",
                            X = 106.79360429730124m,
                            Y = 10.859659403282347m
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8460),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "TD_P8",
                            TenDiaDiem = "TD 8",
                            X = 106.79332274829952m,
                            Y = 10.860122251459547m
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8460),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "LR_P1",
                            TenDiaDiem = "LR 1",
                            X = 106.793929m,
                            Y = 10.858177m
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8470),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "LR_P2",
                            TenDiaDiem = "LR 2",
                            X = 106.794037m,
                            Y = 10.857903m
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8470),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "LR_P3",
                            TenDiaDiem = "LR 3",
                            X = 106.793602m,
                            Y = 10.857721m
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8470),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "LR_P4",
                            TenDiaDiem = "LR 4",
                            X = 106.793973m,
                            Y = 10.857163m
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8470),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "LR_P5",
                            TenDiaDiem = "LR 5",
                            X = 106.79467m,
                            Y = 10.857586m
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(8470),
                            CreatedBy = "system",
                            IsActive = true,
                            MaDiaDiem = "LR_P6",
                            TenDiaDiem = "LR 6",
                            X = 106.794244m,
                            Y = 10.858444m
                        });
                });

            modelBuilder.Entity("GIS.API.Models.Diem_PhanKhu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiaDiemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PhanKhuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhanKhuId");

                    b.HasIndex("DiaDiemId", "PhanKhuId")
                        .IsUnique();

                    b.ToTable("Diem_PhanKhu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7230),
                            CreatedBy = "system",
                            DiaDiemId = 1,
                            IsActive = true,
                            PhanKhuId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 2,
                            IsActive = true,
                            PhanKhuId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 3,
                            IsActive = true,
                            PhanKhuId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 4,
                            IsActive = true,
                            PhanKhuId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 5,
                            IsActive = true,
                            PhanKhuId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 6,
                            IsActive = true,
                            PhanKhuId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 7,
                            IsActive = true,
                            PhanKhuId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 8,
                            IsActive = true,
                            PhanKhuId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 9,
                            IsActive = true,
                            PhanKhuId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 10,
                            IsActive = true,
                            PhanKhuId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 11,
                            IsActive = true,
                            PhanKhuId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 12,
                            IsActive = true,
                            PhanKhuId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 13,
                            IsActive = true,
                            PhanKhuId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 14,
                            IsActive = true,
                            PhanKhuId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 15,
                            IsActive = true,
                            PhanKhuId = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 16,
                            IsActive = true,
                            PhanKhuId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 17,
                            IsActive = true,
                            PhanKhuId = 3
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 18,
                            IsActive = true,
                            PhanKhuId = 3
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7240),
                            CreatedBy = "system",
                            DiaDiemId = 19,
                            IsActive = true,
                            PhanKhuId = 3
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7250),
                            CreatedBy = "system",
                            DiaDiemId = 20,
                            IsActive = true,
                            PhanKhuId = 3
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7250),
                            CreatedBy = "system",
                            DiaDiemId = 21,
                            IsActive = true,
                            PhanKhuId = 3
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7250),
                            CreatedBy = "system",
                            DiaDiemId = 22,
                            IsActive = true,
                            PhanKhuId = 3
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7250),
                            CreatedBy = "system",
                            DiaDiemId = 23,
                            IsActive = true,
                            PhanKhuId = 3
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7250),
                            CreatedBy = "system",
                            DiaDiemId = 24,
                            IsActive = true,
                            PhanKhuId = 3
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7260),
                            CreatedBy = "system",
                            DiaDiemId = 25,
                            IsActive = true,
                            PhanKhuId = 3
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7260),
                            CreatedBy = "system",
                            DiaDiemId = 26,
                            IsActive = true,
                            PhanKhuId = 4
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7260),
                            CreatedBy = "system",
                            DiaDiemId = 27,
                            IsActive = true,
                            PhanKhuId = 4
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7260),
                            CreatedBy = "system",
                            DiaDiemId = 28,
                            IsActive = true,
                            PhanKhuId = 4
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7270),
                            CreatedBy = "system",
                            DiaDiemId = 29,
                            IsActive = true,
                            PhanKhuId = 4
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7270),
                            CreatedBy = "system",
                            DiaDiemId = 30,
                            IsActive = true,
                            PhanKhuId = 4
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7270),
                            CreatedBy = "system",
                            DiaDiemId = 31,
                            IsActive = true,
                            PhanKhuId = 4
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7270),
                            CreatedBy = "system",
                            DiaDiemId = 32,
                            IsActive = true,
                            PhanKhuId = 4
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7270),
                            CreatedBy = "system",
                            DiaDiemId = 33,
                            IsActive = true,
                            PhanKhuId = 4
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7270),
                            CreatedBy = "system",
                            DiaDiemId = 34,
                            IsActive = true,
                            PhanKhuId = 5
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7270),
                            CreatedBy = "system",
                            DiaDiemId = 35,
                            IsActive = true,
                            PhanKhuId = 5
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7270),
                            CreatedBy = "system",
                            DiaDiemId = 36,
                            IsActive = true,
                            PhanKhuId = 5
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7270),
                            CreatedBy = "system",
                            DiaDiemId = 37,
                            IsActive = true,
                            PhanKhuId = 5
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7270),
                            CreatedBy = "system",
                            DiaDiemId = 38,
                            IsActive = true,
                            PhanKhuId = 5
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 49, 20, 401, DateTimeKind.Utc).AddTicks(7270),
                            CreatedBy = "system",
                            DiaDiemId = 39,
                            IsActive = true,
                            PhanKhuId = 5
                        });
                });

            modelBuilder.Entity("GIS.API.Models.KhuVuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MaKhuVuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaKhuVuc")
                        .IsUnique();

                    b.ToTable("KhuVuc", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(9450),
                            CreatedBy = "system",
                            IsActive = true,
                            MaKhuVuc = "KV_CO_KHI",
                            TenKhuVuc = "Khu vực Cơ Khí"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 401, DateTimeKind.Local).AddTicks(9450),
                            CreatedBy = "system",
                            IsActive = true,
                            MaKhuVuc = "KV_KHO_VAN",
                            TenKhuVuc = "Khu Vực Kho Vận"
                        });
                });

            modelBuilder.Entity("GIS.API.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MaNV")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaNV")
                        .IsUnique()
                        .HasFilter("[MaNV] IS NOT NULL");

                    b.HasIndex("PhongBanId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(1720),
                            CreatedBy = "system",
                            Email = "khang.ln@gis.com",
                            HoTen = "Lê Nguyên Khang",
                            IsActive = true,
                            MaNV = "IT0001",
                            NgaySinh = new DateOnly(1900, 1, 1),
                            Password = "BMH+uHV2H/cEek07BDi0KQ==.CO+cIOr2BPWEIc+L+ZEYcpsJKhgFokepsQHGyy23Ils=",
                            PhongBanId = 2,
                            RoleId = 1,
                            SDT = "0900000001",
                            UserName = "khang.ln"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(1720),
                            CreatedBy = "system",
                            Email = "kha.nv@gis.com",
                            HoTen = "Nguyễn Văn Kha",
                            IsActive = true,
                            MaNV = "IT0002",
                            NgaySinh = new DateOnly(1900, 1, 1),
                            Password = "BMH+uHV2H/cEek07BDi0KQ==.CO+cIOr2BPWEIc+L+ZEYcpsJKhgFokepsQHGyy23Ils=",
                            PhongBanId = 2,
                            RoleId = 2,
                            SDT = "0900000002",
                            UserName = "kha.nv"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(1720),
                            CreatedBy = "system",
                            Email = "binh.nt@gis.com",
                            HoTen = "Nguyễn Thanh Bình",
                            IsActive = true,
                            MaNV = "IT0003",
                            NgaySinh = new DateOnly(1900, 1, 1),
                            Password = "ra+TQLJfrnZZY7cjDIHsvw==.QjmgfpqahyadGveo1YwvS6criJp6I2ZM+DNIb2Ism5g=",
                            PhongBanId = 2,
                            RoleId = 3,
                            SDT = "0900000003",
                            UserName = "binh.nt"
                        });
                });

            modelBuilder.Entity("GIS.API.Models.PhanCa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiaDiemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("NgayBD")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKT")
                        .HasColumnType("date");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiaDiemId");

                    b.HasIndex("NhanVienId");

                    b.HasIndex("CaId", "NhanVienId", "DiaDiemId", "NgayBD")
                        .IsUnique();

                    b.ToTable("PhanCa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaId = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(5980),
                            CreatedBy = "system",
                            DiaDiemId = 1,
                            IsActive = true,
                            NgayBD = new DateOnly(2026, 1, 19),
                            NhanVienId = 1
                        },
                        new
                        {
                            Id = 2,
                            CaId = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(5990),
                            CreatedBy = "system",
                            DiaDiemId = 1,
                            IsActive = true,
                            NgayBD = new DateOnly(2026, 1, 19),
                            NhanVienId = 2
                        });
                });

            modelBuilder.Entity("GIS.API.Models.PhanKhu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("KhuVucId")
                        .HasColumnType("int");

                    b.Property<string>("MaPhanKhu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenPhanKhu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhuVucId");

                    b.HasIndex("MaPhanKhu")
                        .IsUnique();

                    b.ToTable("PhanKhu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(7420),
                            CreatedBy = "system",
                            IsActive = true,
                            KhuVucId = 1,
                            MaPhanKhu = "PK_CNC",
                            TenPhanKhu = "Nhà xưởng CNC"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(7420),
                            CreatedBy = "system",
                            IsActive = true,
                            KhuVucId = 1,
                            MaPhanKhu = "PK_HC",
                            TenPhanKhu = "Văn phòng Hành chính"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(7420),
                            CreatedBy = "system",
                            IsActive = true,
                            KhuVucId = 1,
                            MaPhanKhu = "PK_IT",
                            TenPhanKhu = "Văn phòng IT"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(7420),
                            CreatedBy = "system",
                            IsActive = true,
                            KhuVucId = 1,
                            MaPhanKhu = "PK_TD",
                            TenPhanKhu = "Văn phòng Tuyển dụng"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(7420),
                            CreatedBy = "system",
                            IsActive = true,
                            KhuVucId = 1,
                            MaPhanKhu = "PK_LR",
                            TenPhanKhu = "Nhà xưởng lắp ráp"
                        });
                });

            modelBuilder.Entity("GIS.API.Models.PhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MaPB")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("NgayTL")
                        .HasColumnType("date");

                    b.Property<string>("TenPB")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaPB")
                        .IsUnique();

                    b.ToTable("PhongBan", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(8370),
                            CreatedBy = "system",
                            IsActive = true,
                            MaPB = "HR",
                            NgayTL = new DateOnly(2025, 12, 1),
                            TenPB = "Phòng Nhân Sự"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(8370),
                            CreatedBy = "system",
                            IsActive = true,
                            MaPB = "IT",
                            NgayTL = new DateOnly(2025, 12, 1),
                            TenPB = "Phòng CNTT"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(8370),
                            CreatedBy = "system",
                            IsActive = true,
                            MaPB = "AC",
                            NgayTL = new DateOnly(2025, 12, 1),
                            TenPB = "Kế toán"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(8370),
                            CreatedBy = "system",
                            IsActive = true,
                            MaPB = "PD",
                            NgayTL = new DateOnly(2025, 12, 1),
                            TenPB = "Sản xuất"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(8370),
                            CreatedBy = "system",
                            IsActive = true,
                            MaPB = "EX",
                            NgayTL = new DateOnly(2025, 12, 1),
                            TenPB = "Xuất nhập khẩu"
                        });
                });

            modelBuilder.Entity("GIS.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(9210),
                            CreatedBy = "system",
                            IsActive = true,
                            RoleCode = "Admin",
                            RoleName = "Admin Role"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(9210),
                            CreatedBy = "system",
                            IsActive = true,
                            RoleCode = "Manager",
                            RoleName = "Manager Role"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 402, DateTimeKind.Local).AddTicks(9210),
                            CreatedBy = "system",
                            IsActive = true,
                            RoleCode = "Employee",
                            RoleName = "Employee Role"
                        });
                });

            modelBuilder.Entity("GIS.API.Models.TheTu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MaThe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("NgayCap")
                        .HasColumnType("date");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaThe")
                        .IsUnique();

                    b.HasIndex("NhanVienId");

                    b.ToTable("TheTu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 403, DateTimeKind.Local).AddTicks(540),
                            CreatedBy = "system",
                            IsActive = true,
                            MaThe = "CARD01",
                            NgayCap = new DateOnly(2025, 12, 1),
                            NhanVienId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 23, 49, 20, 403, DateTimeKind.Local).AddTicks(550),
                            CreatedBy = "system",
                            IsActive = true,
                            MaThe = "CARD02",
                            NgayCap = new DateOnly(2025, 12, 1),
                            NhanVienId = 1
                        });
                });

            modelBuilder.Entity("GIS.API.Models.ChamCong", b =>
                {
                    b.HasOne("GIS.API.Models.Diem", "Diem")
                        .WithMany("ChamCongs")
                        .HasForeignKey("DiaDiemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIS.API.Models.TheTu", "TheTu")
                        .WithMany("ChamCongs")
                        .HasForeignKey("TheId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diem");

                    b.Navigation("TheTu");
                });

            modelBuilder.Entity("GIS.API.Models.Diem_PhanKhu", b =>
                {
                    b.HasOne("GIS.API.Models.Diem", "Diem")
                        .WithMany("Diem_PhanKhus")
                        .HasForeignKey("DiaDiemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIS.API.Models.PhanKhu", "PhanKhu")
                        .WithMany("Diem_PhanKhus")
                        .HasForeignKey("PhanKhuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diem");

                    b.Navigation("PhanKhu");
                });

            modelBuilder.Entity("GIS.API.Models.NhanVien", b =>
                {
                    b.HasOne("GIS.API.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIS.API.Models.Role", "Role")
                        .WithMany("NhanViens")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongBan");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GIS.API.Models.PhanCa", b =>
                {
                    b.HasOne("GIS.API.Models.Ca", "Ca")
                        .WithMany("PhanCas")
                        .HasForeignKey("CaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIS.API.Models.Diem", "Diem")
                        .WithMany("PhanCas")
                        .HasForeignKey("DiaDiemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GIS.API.Models.NhanVien", "NhanVien")
                        .WithMany("PhanCas")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ca");

                    b.Navigation("Diem");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("GIS.API.Models.PhanKhu", b =>
                {
                    b.HasOne("GIS.API.Models.KhuVuc", "KhuVuc")
                        .WithMany("PhanKhus")
                        .HasForeignKey("KhuVucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhuVuc");
                });

            modelBuilder.Entity("GIS.API.Models.TheTu", b =>
                {
                    b.HasOne("GIS.API.Models.NhanVien", "NhanVien")
                        .WithMany("TheTus")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("GIS.API.Models.Ca", b =>
                {
                    b.Navigation("PhanCas");
                });

            modelBuilder.Entity("GIS.API.Models.Diem", b =>
                {
                    b.Navigation("ChamCongs");

                    b.Navigation("Diem_PhanKhus");

                    b.Navigation("PhanCas");
                });

            modelBuilder.Entity("GIS.API.Models.KhuVuc", b =>
                {
                    b.Navigation("PhanKhus");
                });

            modelBuilder.Entity("GIS.API.Models.NhanVien", b =>
                {
                    b.Navigation("PhanCas");

                    b.Navigation("TheTus");
                });

            modelBuilder.Entity("GIS.API.Models.PhanKhu", b =>
                {
                    b.Navigation("Diem_PhanKhus");
                });

            modelBuilder.Entity("GIS.API.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("GIS.API.Models.Role", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("GIS.API.Models.TheTu", b =>
                {
                    b.Navigation("ChamCongs");
                });
#pragma warning restore 612, 618
        }
    }
}
