// <auto-generated />
using GIS.PERSISTENCE.Abstractions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GIS.PERSISTENCE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GIS.DOMAIN.Entities.Users.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "HR",
                            Code = "HR",
                            Name = "HR"
                        },
                        new
                        {
                            Id = "IT",
                            Code = "IT",
                            Name = "IT"
                        },
                        new
                        {
                            Id = "AC",
                            Code = "AC",
                            Name = "Kế toán"
                        },
                        new
                        {
                            Id = "PD",
                            Code = "PD",
                            Name = "Sản xuất"
                        },
                        new
                        {
                            Id = "EX",
                            Code = "EX",
                            Name = "Xuất nhập khẩu"
                        });
                });

            modelBuilder.Entity("GIS.DOMAIN.Entities.Users.Position", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "HR-MGR",
                            Code = "HR-MGR",
                            DepartmentId = "HR",
                            Name = "Nhân sự trưởng"
                        },
                        new
                        {
                            Id = "HR-STAFF",
                            Code = "HR-STAFF",
                            DepartmentId = "HR",
                            Name = "Nhân sự"
                        },
                        new
                        {
                            Id = "IT-MGR",
                            Code = "IT-MGR",
                            DepartmentId = "IT",
                            Name = "IT trưởng"
                        },
                        new
                        {
                            Id = "IT-DEV",
                            Code = "IT-DEV",
                            DepartmentId = "IT",
                            Name = "Developer"
                        },
                        new
                        {
                            Id = "AC-MGR",
                            Code = "AC-MGR",
                            DepartmentId = "AC",
                            Name = "Kế toán trưởng"
                        },
                        new
                        {
                            Id = "AC-STAFF",
                            Code = "AC-STAFF",
                            DepartmentId = "AC",
                            Name = "Kế toán viên"
                        },
                        new
                        {
                            Id = "PD-MGR",
                            Code = "PD-MGR",
                            DepartmentId = "PD",
                            Name = "Quản đốc"
                        },
                        new
                        {
                            Id = "PD-WORKER",
                            Code = "PD-WORKER",
                            DepartmentId = "PD",
                            Name = "Công nhân"
                        },
                        new
                        {
                            Id = "EX-MGR",
                            Code = "EX-MGR",
                            DepartmentId = "EX",
                            Name = "Trưởng xuất nhập khẩu"
                        },
                        new
                        {
                            Id = "EX-STAFF",
                            Code = "EX-STAFF",
                            DepartmentId = "EX",
                            Name = "Nhân viên xuất nhập khẩu"
                        });
                });

            modelBuilder.Entity("GIS.DOMAIN.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "IT0001",
                            Email = "khang.ln@gis.com",
                            IsActive = true,
                            IsAdmin = true,
                            Name = "Lê Nguyên Khang",
                            Password = "BMH+uHV2H/cEek07BDi0KQ==.CO+cIOr2BPWEIc+L+ZEYcpsJKhgFokepsQHGyy23Ils=",
                            Phone = "0900000001",
                            PositionId = "IT-DEV",
                            UserName = "khang.ln"
                        },
                        new
                        {
                            Id = 2,
                            Code = "IT0002",
                            Email = "kha.nv@gis.com",
                            IsActive = true,
                            IsAdmin = false,
                            Name = "Nguyễn Văn Kha",
                            Password = "BMH+uHV2H/cEek07BDi0KQ==.CO+cIOr2BPWEIc+L+ZEYcpsJKhgFokepsQHGyy23Ils=",
                            Phone = "0900000002",
                            PositionId = "IT-DEV",
                            UserName = "kha.nv"
                        },
                        new
                        {
                            Id = 3,
                            Code = "IT0003",
                            Email = "binh.nt@gis.com",
                            IsActive = true,
                            IsAdmin = false,
                            Name = "Nguyễn Thanh Bình",
                            Password = "BMH+uHV2H/cEek07BDi0KQ==.CO+cIOr2BPWEIc+L+ZEYcpsJKhgFokepsQHGyy23Ils=",
                            Phone = "0900000003",
                            PositionId = "IT-DEV",
                            UserName = "binh.nt"
                        },
                        new
                        {
                            Id = 4,
                            Code = "IT0004",
                            Email = "thao.np@gis.com",
                            IsActive = true,
                            IsAdmin = false,
                            Name = "Nguyễn Phương Thảo",
                            Password = "BMH+uHV2H/cEek07BDi0KQ==.CO+cIOr2BPWEIc+L+ZEYcpsJKhgFokepsQHGyy23Ils=",
                            Phone = "0900000004",
                            PositionId = "AC-MGR",
                            UserName = "thao.np"
                        },
                        new
                        {
                            Id = 5,
                            Code = "IT0005",
                            Email = "lan.dtp@gis.com",
                            IsActive = true,
                            IsAdmin = false,
                            Name = "Đào Thị Phương Lan",
                            Password = "BMH+uHV2H/cEek07BDi0KQ==.CO+cIOr2BPWEIc+L+ZEYcpsJKhgFokepsQHGyy23Ils=",
                            Phone = "0900000005",
                            PositionId = "EX-MGR",
                            UserName = "lan.dtp"
                        });
                });

            modelBuilder.Entity("GIS.DOMAIN.Entities.Users.Position", b =>
                {
                    b.HasOne("GIS.DOMAIN.Entities.Users.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GIS.DOMAIN.Entities.Users.User", b =>
                {
                    b.HasOne("GIS.DOMAIN.Entities.Users.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
